export const criarAplicadorVazio = (userId = null) => ({
  user_id: userId,
  full_name: '',
  birth_date: '',
  gender: '',
  nationality: '',
  address: '',
  phone_number: '',
  cpf: '',
  rg: '',
  academic_background: '',
  attachments: [],
  position: '',
  department: '',
  admission_date: '',
  work_scale: '',
  observations: '',
  role: 'aplicator', 
});
